services:
  codenames_db:
    image: codenames.azurecr.io/postgres:latest
    build: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codenames
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  app:
    image: codenames.azurecr.io/service:latest
    build: service
    environment:
      - DB_HOST=codenames_db
      - POSTGRES_DB=codenames
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - codenames_db

  frontend:
    image: codenames.azurecr.io/frontend:latest
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080 
    expose:
      - "80"
    ports:
      - "80:80"