spring.application.name=codenames
spring.datasource.url=jdbc:postgresql://${DB_HOST:codenames_db}:5432/${POSTGRES_DB:codenames}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect