INSERT INTO public.word (word) VALUES
	 ('Africa'),
	 ('Agent'),
	 ('Air'),
	 ('Alien'),
	 ('Alps'),
	 ('Amazon'),
	 ('Ambulance'),
	 ('America'),
	 ('Angel'),
	 ('Antarctica');
INSERT INTO public.word (word) VALUES
	 ('Apple'),
	 ('Arm'),
	 ('Atlantis'),
	 ('Australia'),
	 ('Aztec'),
	 ('Back'),
	 ('Ball'),
	 ('Band'),
	 ('Bank'),
	 ('Bar');
INSERT INTO public.word (word) VALUES
	 ('Bark'),
	 ('Bat'),
	 ('Battery'),
	 ('Beach'),
	 ('Bear'),
	 ('Beat'),
	 ('Bed'),
	 ('Beijing'),
	 ('Bell'),
	 ('Belt');
INSERT INTO public.word (word) VALUES
	 ('Berlin'),
	 ('Bermuda'),
	 ('Berry'),
	 ('Bill'),
	 ('Block'),
	 ('Board'),
	 ('Bolt'),
	 ('Bomb'),
	 ('Bond'),
	 ('Boom');
INSERT INTO public.word (word) VALUES
	 ('Boot'),
	 ('Bottle'),
	 ('Bow'),
	 ('Box'),
	 ('Bridge'),
	 ('Brush'),
	 ('Buck'),
	 ('Buffalo'),
	 ('Bug'),
	 ('Bugle');
INSERT INTO public.word (word) VALUES
	 ('Button'),
	 ('Calf'),
	 ('Canada'),
	 ('Cap'),
	 ('Capital'),
	 ('Car'),
	 ('Card'),
	 ('Carrot'),
	 ('Casino'),
	 ('Cast');
INSERT INTO public.word (word) VALUES
	 ('Cat'),
	 ('Cell'),
	 ('Centaur'),
	 ('Center'),
	 ('Chair'),
	 ('Change'),
	 ('Charge'),
	 ('Check'),
	 ('Chest'),
	 ('Chick');
INSERT INTO public.word (word) VALUES
	 ('China'),
	 ('Chocolate'),
	 ('Church'),
	 ('Circle'),
	 ('Cliff'),
	 ('Cloak'),
	 ('Club'),
	 ('Code'),
	 ('Cold'),
	 ('Comic');
INSERT INTO public.word (word) VALUES
	 ('Compound'),
	 ('Concert'),
	 ('Conductor'),
	 ('Contract'),
	 ('Cook'),
	 ('Copper'),
	 ('Cotton'),
	 ('Court'),
	 ('Cover'),
	 ('Crane');
INSERT INTO public.word (word) VALUES
	 ('Crash'),
	 ('Cricket'),
	 ('Cross'),
	 ('Crown'),
	 ('Cycle'),
	 ('Czech'),
	 ('Dance'),
	 ('Date'),
	 ('Day'),
	 ('Death');
INSERT INTO public.word (word) VALUES
	 ('Deck'),
	 ('Degree'),
	 ('Diamond'),
	 ('Dice'),
	 ('Dinosaur'),
	 ('Disease'),
	 ('Doctor'),
	 ('Dog'),
	 ('Draft'),
	 ('Dragon');
INSERT INTO public.word (word) VALUES
	 ('Dress'),
	 ('Drill'),
	 ('Drop'),
	 ('Duck'),
	 ('Dwarf'),
	 ('Eagle'),
	 ('Egypt'),
	 ('Embassy'),
	 ('Engine'),
	 ('England');
INSERT INTO public.word (word) VALUES
	 ('Europe'),
	 ('Eye'),
	 ('Face'),
	 ('Fair'),
	 ('Fall'),
	 ('Fan'),
	 ('Fence'),
	 ('Field'),
	 ('Fighter'),
	 ('Figure');
INSERT INTO public.word (word) VALUES
	 ('File'),
	 ('Film'),
	 ('Fire'),
	 ('Fish'),
	 ('Flute'),
	 ('Fly'),
	 ('Foot'),
	 ('Force'),
	 ('Forest'),
	 ('Fork');
INSERT INTO public.word (word) VALUES
	 ('France'),
	 ('Game'),
	 ('Gas'),
	 ('Genius'),
	 ('Germany'),
	 ('Ghost'),
	 ('Giant'),
	 ('Glass'),
	 ('Glove'),
	 ('Gold');
INSERT INTO public.word (word) VALUES
	 ('Grace'),
	 ('Grass'),
	 ('Greece'),
	 ('Green'),
	 ('Ground'),
	 ('Ham'),
	 ('Hand'),
	 ('Hawk'),
	 ('Head'),
	 ('Heart');
INSERT INTO public.word (word) VALUES
	 ('Helicopter'),
	 ('Himalayas'),
	 ('Hole'),
	 ('Hollywood'),
	 ('Honey'),
	 ('Hood'),
	 ('Hook'),
	 ('Horn'),
	 ('Horse'),
	 ('Horseshoe');
INSERT INTO public.word (word) VALUES
	 ('Hospital'),
	 ('Hotel'),
	 ('Ice'),
	 ('Ice cream'),
	 ('India'),
	 ('Iron'),
	 ('Ivory'),
	 ('Jack'),
	 ('Jam'),
	 ('Jet');
INSERT INTO public.word (word) VALUES
	 ('Jupiter'),
	 ('Kangaroo'),
	 ('Ketchup'),
	 ('Key'),
	 ('Kid'),
	 ('King'),
	 ('Kiwi'),
	 ('Knife'),
	 ('Knight'),
	 ('Lab');
INSERT INTO public.word (word) VALUES
	 ('Lap'),
	 ('Laser'),
	 ('Lawyer'),
	 ('Lead'),
	 ('Lemon'),
	 ('Leprechaun'),
	 ('Life'),
	 ('Light'),
	 ('Limousine'),
	 ('Line');
INSERT INTO public.word (word) VALUES
	 ('Link'),
	 ('Lion'),
	 ('Litter'),
	 ('Loch ness'),
	 ('Lock'),
	 ('Log'),
	 ('London'),
	 ('Luck'),
	 ('Mail'),
	 ('Mammoth');
INSERT INTO public.word (word) VALUES
	 ('Maple'),
	 ('Marble'),
	 ('March'),
	 ('Mass'),
	 ('Match'),
	 ('Mercury'),
	 ('Mexico'),
	 ('Microscope'),
	 ('Millionaire'),
	 ('Mine');
INSERT INTO public.word (word) VALUES
	 ('Mint'),
	 ('Missile'),
	 ('Model'),
	 ('Mole'),
	 ('Moon'),
	 ('Moscow'),
	 ('Mount'),
	 ('Mouse'),
	 ('Mouth'),
	 ('Mug');
INSERT INTO public.word (word) VALUES
	 ('Nail'),
	 ('Needle'),
	 ('Net'),
	 ('New york'),
	 ('Night'),
	 ('Ninja'),
	 ('Note'),
	 ('Novel'),
	 ('Nurse'),
	 ('Nut');
INSERT INTO public.word (word) VALUES
	 ('Octopus'),
	 ('Oil'),
	 ('Olive'),
	 ('Olympus'),
	 ('Opera'),
	 ('Orange'),
	 ('Organ'),
	 ('Palm'),
	 ('Pan'),
	 ('Pants');
INSERT INTO public.word (word) VALUES
	 ('Paper'),
	 ('Parachute'),
	 ('Park'),
	 ('Part'),
	 ('Pass'),
	 ('Paste'),
	 ('Penguin'),
	 ('Phoenix'),
	 ('Piano'),
	 ('Pie');
INSERT INTO public.word (word) VALUES
	 ('Pilot'),
	 ('Pin'),
	 ('Pipe'),
	 ('Pirate'),
	 ('Pistol'),
	 ('Pit'),
	 ('Pitch'),
	 ('Plane'),
	 ('Plastic'),
	 ('Plate');
INSERT INTO public.word (word) VALUES
	 ('Platypus'),
	 ('Play'),
	 ('Plot'),
	 ('Point'),
	 ('Poison'),
	 ('Pole'),
	 ('Police'),
	 ('Pool'),
	 ('Port'),
	 ('Post');
INSERT INTO public.word (word) VALUES
	 ('Pound'),
	 ('Press'),
	 ('Princess'),
	 ('Pumpkin'),
	 ('Pupil'),
	 ('Pyramid'),
	 ('Queen'),
	 ('Rabbit'),
	 ('Racket'),
	 ('Ray');
INSERT INTO public.word (word) VALUES
	 ('Revolution'),
	 ('Ring'),
	 ('Robin'),
	 ('Robot'),
	 ('Rock'),
	 ('Rome'),
	 ('Root'),
	 ('Rose'),
	 ('Roulette'),
	 ('Round');
INSERT INTO public.word (word) VALUES
	 ('Row'),
	 ('Ruler'),
	 ('Satellite'),
	 ('Saturn'),
	 ('Scale'),
	 ('School'),
	 ('Scientist'),
	 ('Scorpion'),
	 ('Screen'),
	 ('Scuba diver');
INSERT INTO public.word (word) VALUES
	 ('Seal'),
	 ('Server'),
	 ('Shadow'),
	 ('Shakespeare'),
	 ('Shark'),
	 ('Ship'),
	 ('Shoe'),
	 ('Shop'),
	 ('Shot'),
	 ('Sink');
INSERT INTO public.word (word) VALUES
	 ('Skyscraper'),
	 ('Slip'),
	 ('Slug'),
	 ('Smuggler'),
	 ('Snow'),
	 ('Snowman'),
	 ('Sock'),
	 ('Soldier'),
	 ('Soul'),
	 ('Sound');
INSERT INTO public.word (word) VALUES
	 ('Space'),
	 ('Spell'),
	 ('Spider'),
	 ('Spike'),
	 ('Spine'),
	 ('Spot'),
	 ('Spring'),
	 ('Spy'),
	 ('Square'),
	 ('Stadium');
INSERT INTO public.word (word) VALUES
	 ('Staff'),
	 ('Star'),
	 ('State'),
	 ('Stick'),
	 ('Stock'),
	 ('Straw'),
	 ('Stream'),
	 ('Strike'),
	 ('String'),
	 ('Sub');
INSERT INTO public.word (word) VALUES
	 ('Suit'),
	 ('Superhero'),
	 ('Swing'),
	 ('Switch'),
	 ('Table'),
	 ('Tablet'),
	 ('Tag'),
	 ('Tail'),
	 ('Tap'),
	 ('Teacher');
INSERT INTO public.word (word) VALUES
	 ('Telescope'),
	 ('Temple'),
	 ('Theater'),
	 ('Thief'),
	 ('Thumb'),
	 ('Tick'),
	 ('Tie'),
	 ('Time'),
	 ('Tokyo'),
	 ('Tooth');
INSERT INTO public.word (word) VALUES
	 ('Torch'),
	 ('Tower'),
	 ('Track'),
	 ('Train'),
	 ('Triangle'),
	 ('Trip'),
	 ('Trunk'),
	 ('Tube'),
	 ('Turkey'),
	 ('Undertaker');
INSERT INTO public.word (word) VALUES
	 ('Unicorn'),
	 ('Vacuum'),
	 ('Van'),
	 ('Vet'),
	 ('Wake'),
	 ('Wall'),
	 ('War'),
	 ('Washer'),
	 ('Washington'),
	 ('Watch');
INSERT INTO public.word (word) VALUES
	 ('Water'),
	 ('Wave'),
	 ('Web'),
	 ('Well'),
	 ('Whale'),
	 ('Whip'),
	 ('Wind'),
	 ('Witch'),
	 ('Worm'),
	 ('Yard');
